apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: $ARGOCD_ADMIN_PASSWORD
  server.secretkey: $ARGOCD_SERVER_SECRET_KEY
  # GitHub webhook secret
  webhook.github.secret: $GITHUB_WEBHOOK_SECRET
  # GitLab webhook secret
  webhook.gitlab.secret: $GITLAB_WEBHOOK_SECRET
  # OIDC secrets
  dex.github.clientSecret: $GITHUB_CLIENT_SECRET
  # Repository SSH key
  repository.credentials: |
    - url: git@github.com:betuanminh22032003
      passwordSecret:
        name: github-credentials
        key: password
      usernameSecret:
        name: github-credentials
        key: username
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
type: Opaque
stringData:
  username: $GITHUB_USERNAME
  password: $GITHUB_PERSONAL_ACCESS_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
type: Opaque
stringData:
  password: $ARGOCD_ADMIN_PASSWORD
